config/routes.rb
Rails.application.routes.draw do
	get 'forum/index'

  resources :users, except: [:create]
  resources :user_forms, only: [:create]

	resources :topics do
		resources :posts
  end

	get 'sessions/new', to: 'sessions#new'
	post 'sessions/create', to: 'sessions#create'
	delete 'sessions/destroy', to: 'sessions#destroy'

	root 'forum#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :topic
	belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :user
  has_many :posts
  
  def self.find_or_nil(find_id)
    Topic.find_by(id: find_id) || NullTopic.new
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  
  has_secure_password

  has_many :topics
  has_many :posts
  has_one :user_detail
  has_one_attached :avatar
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user
end

app/models/user_form.rb
class UserForm
  include ActiveModel::Model
  validate :validate_children
  validates :name, length: {minimum: 6}
  validates :password, length:{minimum: 6}
  
  attr_accessor :name, :email, :password, :password_confirmation, :address_line_1, :address_line_2, :address_line_3, :avatar

  def save
    return false if invalid?
    user.save!
    user_detail.save!
  end

  def user
    @user ||= User.new(name: name, email: email, password: password, password_confirmation: password_confirmation)
    @user.avatar.attach(avatar)
    @user
  end

  def user_detail
    @user_detail ||= user.build_user_detail(address_line_1: address_line_1, address_line_2: address_line_2, address_line_3: address_line_3)
  end

  private
  def validate_children
    add_errors(user.errors) if user.invalid?
    add_errors(user_detail.errors) if user_detail.invalid?
  end

  def add_errors(errors_to_add)
    errors_to_add.each do |attribute, message|
      errors.add(attribute, message)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

end

app/controllers/forum_controller.rb
class ForumController < ApplicationController

	def index
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in
	
	def create
		@topic = Topic.find params[:topic_id]
		@post = @topic.posts.new(posts_params)
		@post.user_id = current_user.id
		@post.save
		redirect_to topic_path(@topic)
	end

	def destroy
		post = Post.find_by(id: params[:post_id])
		post.destroy if post
	end

	private
		def posts_params
			params.require(:post).permit(:name, :body)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(name: params[:name])
		if user.nil?
			flash.now[:danger] = 'Username is incorrect'
			render 'new' and return
		end
		if user.authenticate(params[:password])
			log_in user
			redirect_to user_path(user)
		else
			flash.now[:danger] = 'Password is incorrect'
			render 'new'
		end
	end

	def destroy
		log_out
		render 'new'
	end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	before_action :logged_in, except: [:index, :show]
	def index
		@topics = Topic.all
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = Topic.new(topic_params)
		@topic.user_id = current_user.id
		if @topic.save
			redirect_to topics_path
		else
			render 'new'
		end
	end

	def show
    @topic = Topic.find_or_nil(params[:id])
    @posts = PostDecorator.decorate_collection(@topic.posts)
	end

	def destroy
		Topic.find(params[:id]).destroy
	end

	private
		def topic_params
			params.require(:topic).permit(:name)
		end
end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  def create
    @user_form = UserForm.new(user_form_params)
    if @user_form.save
      log_in @user_form.user
      redirect_to root_url, notice: 'Registration complete'
    else
      flash[:danger] = @user_form.errors.full_messages if @user_form.errors.any?
      redirect_to new_user_path
    end
  end

  private
  def user_form_params
    params.require(:user_form).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in, except: [:new, :create]

	def new
		@user_form = UserForm.new
	end

	def show
		@user = current_user
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to user_path(@user)
		else
			flash[:danger] = @user.errors.full_messages if @user.errors.any?
			redirect_to edit_user_path(@user)
		end
	end

	def destroy
		current_user.destroy
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session[:user_id] = nil
	end

	def logged_in?
		!current_user.nil?
	end

	def logged_in
		if !logged_in?
			flash[:danger] = 'Log in to proceed'
			redirect_to sessions_new_path
		end
	end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash.html.haml
- flash.each do |_, msg|
	- if msg.kind_of?(Array)
		- msg.each do |m|
			.flash_tag= m
	- else
		.flash_tag= msg

app/views/application/_menu.html.haml
#menu_bar
	%ul
		%li= link_to 'Home', root_path
		%li= link_to 'Topics', topics_path
		- if logged_in?
			%li= link_to 'My account', user_path(current_user)
			%li= link_to 'Log out', sessions_destroy_path, method: :delete
		- else
			%li= link_to 'Create account', new_user_path
			%li= link_to 'Log in', sessions_new_path
		

app/views/forum/index.html.haml
%h1 Forum!

= render 'application/menu'

.text
	Hi! My name is Adrian.
.text
	I am a student of Computer Science at the University of Technology in Wrocław. 
.text
	The page you are looking at is my Ruby on Rails project. 
.text
	I hope you will enjoy it!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Forum
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_form.html.haml
= form_with model: [@topic, @topic.posts.build] do |form|
	= form.label 'New post: '
	%br/
	= form.text_area :body
	= form.hidden_field :user_id, value: current_user.id
	= form.hidden_field :topic_id, value: @topic.id
	= form.submit 'Post it!'

app/views/posts/_posts.html.haml
%ul
  - @posts.each do |post|
    %li
      = post.user_name
      = post.delete_and_edit_links
      %p.text= post.body

app/views/topics/_topics.html.haml
%ol
	- topics.each do |topic|
		%li
			= topic.name
			= link_to 'Read', topic_path(topic)

app/views/topics/index.html.haml
%h1 List of all topics

= render 'application/menu'
#topics= render 'topics', topics: @topics

.link= link_to 'New topic', new_topic_path

app/views/topics/new.html.haml
%h1 Create new topic

= render 'application/menu'
= render 'application/flash'

= form_with model: @topic, local: true do |form|
	%p
		= form.label 'Name of the topic'
		%br/
		= form.text_field :name

	= form.submit

app/views/topics/show.html.haml
%h1= "Topic: #{@topic.name}"

= render 'application/menu'

#posts= render 'posts/posts'
#new_post= render 'posts/form' if logged_in?

= link_to 'Remove topic', topic_path(@topic), method: :delete, confirm: {data: 'Are you sure?'}

app/views/users/_form.html.haml
= simple_form_for @user_form do |form|
  = form.input :name, required: true, input_html: { maxlength: 20 }
  = form.input :email, required: true
  = form.input :password, required: true
  = form.input :password_confirmation, required: true
  = form.input :address_line_1
  = form.input :address_line_2
  = form.input :address_line_3
  = form.label :choose_avatar
  = form.file_field :avatar
  = form.submit 'Create Account'

app/views/users/edit.html.haml
%h1 Update your info

= render 'application/menu'
= render 'application/flash'
= render 'form'

app/views/users/new.html.haml
%h1 Create new account

= render 'application/menu'
= render 'application/flash'
= render 'form'

app/views/users/show.html.haml
%h1= "Hi #{@user.name}!"
= image_tag @user.avatar

= render 'application/menu'

.text Here is the list of your topics:
#topics= render 'topics/topics', topics: @user.topics	

.link=	link_to 'Edit account', edit_user_path(@user), class: 'link'
.link= link_to 'Delete account', user_path(@user), method: :delete